name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v1
        with:
          origin: 'https://git.sinanmohd.com/nixos'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
