name: Sync Upstream

env:
  UPSTREAM_URL: "https://git.sinanmohd.com/nixos.git"
  WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  UPSTREAM_BRANCH: "master"
  DOWNSTREAM_BRANCH: "main"

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Upstream
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
          push_args: "-f"
          merge_args: "--allow-unrelated-histories"
